services:
  memharbor_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --chdir /app config.wsgi:application --bind 0.0.0.0:8001
    env_file:
      - .env
    expose:
      - "8001"
    volumes:
      - memharbor_data:/app/db.sqlite3
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - memharbor_server
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYTY5MDU0OTAxNDNiYTdmNDU4MzQxNWIzMjYzMmM1NjQiLCJ0IjoiY2IwNWZiMDgtYzFkNy00M2Q5LWFmMjktZWM3ZGYzOGJiNGUwIiwicyI6Ik9UUXpZak14TWpndFpERXlaUzAwT0RnekxUazBNRFV0TmpnM00ySTBNREF5WXpreiJ9
    restart: unless-stopped

volumes:
  memharbor_data:
