version: '3.8'

services:
  memharbor:
    build: .
    container_name: memharbor_server
    ports:
      - "8001:8001"
    restart: always
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
